aws:
  access_key_id: YOUR_AWS_ACCESS_KEY_HERE
  secret_access_key: YOUR_AWS_SECRET_KEY_HERE
  
benchmark:
  
  # Which AWS keypair to use for ssh conenctions (used by ansible)
  keypairname: "cbmongo"
  
  # Which AWS security group to use?  (NOTE: may be ignored if using a subnet)
  secgroups: ["avcbmongobenchmark"]
  
  # AWS AMI to use for the YCSB client VMs. NOTE: this is likely a custom AMI 
  # with requiretty disabled for sudo access for the ssh.username below. It should 
  # also have enhanced newtorking enabled.
  db_ami: "ami-f0718290"
  # AWS type (size) to use for the DB VMs  
  db_size: "c3.8xlarge"

  # AWS AMI to use for the YCSB client VMs  
  client_ami: "ami-f0718290"
  # AWS type (size) to use for the YCSB client VMs  
  client_size: "c3.8xlarge"

  # Which subnet to use?  Enhanced networking *should* be more consistent within a single subnet
  aws_subnet: "subnet-REPLACEME"
  
  # Which AWS Region?
  aws_region: "us-west-2"

  # Which AWS Availability Zone?
  aws_availability_zone: "us-west-2b"
  
ssh:
  # This user is defined in the AMI (and should have sudo/requiretty disabled)
  username: centos
  
  # Path to your private key file (generated by AWS)
  private_key_path: /some/path/to/cbmongo.pem
    
