---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- include: '{{java_jdk_type}}.yml'

- name: set JAVA_HOME
  become: yes
  become_user: root
  with_items:
    - etc/profile.d/java.sh
  template: >
    src={{item}}.j2
    dest=/{{item}}
    mode=0644
